apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  namespace: users
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: us-central1-docker.pkg.dev/PROJECT_ID/microservices-repo/users-service:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP