# users-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: users
spec:
  selector:
    app: users
  ports:
    - port: 80       # exposed port in cluster
      targetPort: 8080 # container port
  type: ClusterIP